apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:  
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka-service:9093"
          ports:
            - containerPort: 9000  

---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-service
spec:
  selector:
    app: kafdrop
  ports:
    - protocol: TCP  
      port: 9000  
      targetPort: 9000  
      nodePort: 30003  
  type: NodePort
