apiVersion: apps/v1
kind: Deployement
metadata: 
  name: customer-service
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: customer-service
  template: 
    containers:
      - name: customer-service
        image: customer-service
        imagePullPolicy: Never
        ports: 
          containerPort: 3002
---
apiVersion: v1
kind: Service
metadata: 
  name: customer-service-service
spec: 
  selector:
    app: customer-service
  ports: 
    protocol: TCP
    port: 3000
    targetPort: 3002
    nodePort: 300012
  type: NodePort