apiVersion: apps/v1
kind: Deployement
metadata: 
  name: inventory-service
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: inventory-service
  template: 
    containers:
      - name: inventory-service
        image: inventory-service
        imagePullPolicy: Never
        ports: 
          containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-service
spec:   
  selector:   
    app: inventory-service
  ports: 
    protocol: TCP
    port: 3000
    targetPort: 3001
    nodePort: 300011
  type: NodePort