apiVersion: apps/v1
kind: Deployement
metadata: 
  name: order-service
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: order-service
  template: 
    containers:
      - name: order-service
        image: order-service
        imagePullPolicy: Never
        ports: 
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata: 
  name: order-service-service
spec: 
  selector: 
    app: order-service
  ports: 
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 300010
  type: NodePort