apiVersion: apps/v1
kink: Deployment
metadata: 
  name: kafka
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: kafka
  template: 
    metadata: 
      labels: 
        app: kafka
    spec:
      containers: 
        - name: 
          image: 
          restart: always
          env: 
            - KAFKA_BROKER_ID: 1
            - KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            - KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
            - ALLOW_PLAINTEXT_LISTENER: yes
            - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          ports: 
            - containerPort:  9092
            - containerPort: 9093
               
---
apiVersion: v1
kind: Service
metadata: 
  app: kafka-service
spec: 
  selector: 
    app: kafka
  ports: 
    - protocol: TCP
      port: 9000
      targetPort: 9092
      nodePort: 300002